const artists=[
 {name:'Chris Brown',bio:'R&B • Pop • Performer',image:'https://img.youtube.com/vi/mH76VvWkNwA/maxresdefault.jpg',links:{Website:'https://chrisbrownworld.com/',YouTube:'https://www.youtube.com/@ChrisBrownTV',Instagram:'https://www.instagram.com/chrisbrownofficial/',TikTok:'https://www.tiktok.com/@chrisbrownofficial',Facebook:'https://www.facebook.com/chrisbrown/',X:'https://x.com/chrisbrown'}},
 {name:'SZA',bio:'R&B • Soul • Songwriter',image:'https://img.youtube.com/vi/MSRcC626prw/maxresdefault.jpg',links:{YouTube:'https://www.youtube.com/@sza',Instagram:'https://www.instagram.com/sza/',Website:'https://szactrl.com/'}},
 {name:'Beyoncé',bio:'Pop • R&B • Icon',image:'https://img.youtube.com/vi/Ob7vObnFUJc/maxresdefault.jpg',links:{Website:'https://www.beyonce.com/',YouTube:'https://www.youtube.com/@beyonce',Instagram:'https://www.instagram.com/beyonce/'}},
 {name:'Usher',bio:'R&B • Pop • Performer',image:'https://img.youtube.com/vi/3AszPTJXIgM/maxresdefault.jpg',links:{Website:'https://www.usherworld.com/',YouTube:'https://www.youtube.com/@Usher',Instagram:'https://www.instagram.com/usher/'}},
 {name:'Rihanna',bio:'Pop • R&B • Entrepreneur',image:'https://img.youtube.com/vi/lWA2pjMjpBs/maxresdefault.jpg',links:{YouTube:'https://www.youtube.com/@rihanna',Instagram:'https://www.instagram.com/badgalriri/'}},
 {name:'Bruno Mars',bio:'Pop • Funk • R&B',image:'https://img.youtube.com/vi/UqyT8IEBkvY/maxresdefault.jpg',links:{Website:'https://www.brunomars.com/',YouTube:'https://www.youtube.com/@brunomars',Instagram:'https://www.instagram.com/brunomars/'}}
];
const music=[
 ['Questions','Official video','mH76VvWkNwA'],['Under The Influence','Official video','h2kZ7Cw5fSc'],['No Guidance','Official video','6L_k74BOLag'],['Go Crazy','Official video','dPhwbZBvW2o'],['Loyal','Official video','JXRN_LkCa_o'],['Talm\' Bout','Official video','hl1zPbCx4L0']
];
const style=[['Jordan energy','Sneaker edit','photo-1552346154-21d32810aba3'],['Streetwear','Everyday cool','photo-1529139574466-a303027c1d8b'],['Denim days','Classic fit','photo-1541099649105-f69ad21f3246'],['Dress up','Night-out look','photo-1595777457583-95e059d581b8'],['Jacket edit','Layer it','photo-1551028719-00167b16eac5']];
const beauty=[['Makeup mood','Build your look','photo-1596462502278-27bfdc403348'],['Scent story','Find a signature','photo-1541643600914-78b084683601'],['Nail art','Color play','photo-1604654894610-df63bc536371'],['Hair care','Healthy shine','photo-1522337360788-8b13dee7a37e'],['Lashes','Finish the look','photo-1583001931096-959e9a1a6223']];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function mediaCard([title,sub,id]){return `<article class="media-card"><img loading="lazy" src="https://img.youtube.com/vi/${id}/hqdefault.jpg" alt="${title} video thumbnail"><h4>${title}</h4><p>${sub}</p><a href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener">▶ Watch on YouTube</a></article>`}
function productCard([title,sub,img],type){return `<article class="product-card"><img loading="lazy" src="https://images.unsplash.com/${img}?auto=format&fit=crop&w=600&q=80" alt="${title}"><h4>${title}</h4><p>${sub}</p></article>`}
$('#musicRail').innerHTML=music.map(mediaCard).join(''); $('#styleRail').innerHTML=style.map(x=>productCard(x,'style')).join(''); $('#beautyRail').innerHTML=beauty.map(x=>productCard(x,'beauty')).join('');
function selectArtist(a){$('#artistName').textContent=a.name;$('#artistBio').textContent=a.bio;$('#artistImage').src=a.image;$('#artistImage').alt=`${a.name} official video still`;$('#artistLinks').innerHTML=Object.entries(a.links).map(([k,v])=>`<a href="${v}" target="_blank" rel="noopener">${k}</a>`).join('');$('#openChat').innerHTML=`<span>✦</span> Ask AI about ${a.name.split(' ')[0]}`;$('#chatTitle').textContent=`Ask about ${a.name}`;$('#searchSuggestions').innerHTML='';$('#artistFeature').scrollIntoView({behavior:'smooth',block:'center'});localStorage.setItem('khilaArtist',a.name)}
selectArtist(artists.find(a=>a.name===localStorage.getItem('khilaArtist'))||artists[0]);
function showSuggestions(){const q=$('#artistSearch').value.trim().toLowerCase();const matches=artists.filter(a=>a.name.toLowerCase().includes(q));$('#searchSuggestions').innerHTML=(q?matches:artists).slice(0,5).map(a=>`<button data-artist="${a.name}">${a.name}<small> — ${a.bio}</small></button>`).join('')}
$('#artistSearch').addEventListener('input',showSuggestions);$('#artistSearch').addEventListener('focus',showSuggestions);$('#searchSuggestions').addEventListener('click',e=>{const b=e.target.closest('[data-artist]');if(b){selectArtist(artists.find(a=>a.name===b.dataset.artist));$('#artistSearch').value=b.dataset.artist}});$('#searchBtn').onclick=()=>{const q=$('#artistSearch').value.toLowerCase();const a=artists.find(a=>a.name.toLowerCase().includes(q));a?selectArtist(a):window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent($('#artistSearch').value+' official artist')}`,'_blank')};
$$('[data-slider]').forEach(b=>b.onclick=()=>$('#'+b.dataset.slider).scrollBy({left:Number(b.dataset.dir)*330,behavior:'smooth'}));
$$('[data-shop]').forEach(b=>b.onclick=()=>{const term=$('#'+b.dataset.shop).value;window.open(`https://www.google.com/search?tbm=shop&q=${encodeURIComponent(term)}`,'_blank','noopener')});
$$('[data-platform]').forEach(a=>a.onclick=e=>{e.preventDefault();const term=$('#styleSelect').value;const urls={Pinterest:`https://www.pinterest.com/search/pins/?q=${encodeURIComponent(term+' outfit')}`,Instagram:`https://www.instagram.com/explore/search/keyword/?q=${encodeURIComponent(term+' fashion')}`,TikTok:`https://www.tiktok.com/search?q=${encodeURIComponent(term+' fashion')}`};window.open(urls[a.dataset.platform],'_blank','noopener')});
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}tick();setInterval(tick,1000);
async function weather(lat=36.17,lon=-115.14,city='Las Vegas'){try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code&temperature_unit=fahrenheit`);const d=await r.json(),c=d.current.weather_code;$('#weatherTemp').textContent=Math.round(d.current.temperature_2m)+'°';$('#weatherCity').textContent=city;$('#weatherText').textContent=c<3?'Clear skies':c<50?'Cloudy':c<70?'Light rain':'Weather nearby';$('#weatherIcon').textContent=c<3?'☀️':c<50?'☁️':'🌧️'}catch{$('#weatherText').textContent='Forecast unavailable offline'}}weather();$('#useLocation').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>weather(p.coords.latitude,p.coords.longitude,'Your location'),()=>$('#weatherText').textContent='Location permission was not enabled');
$('.nav-toggle').onclick=()=>{const n=$('.nav-links');n.classList.toggle('open');$('.nav-toggle').setAttribute('aria-expanded',n.classList.contains('open'))};$$('.nav-links a').forEach(a=>a.onclick=()=>$('.nav-links').classList.remove('open'));
const openChat=()=>{$('#chatPanel').classList.add('open');$('#scrim').classList.add('show');$('#chatPanel').setAttribute('aria-hidden','false')},closeChat=()=>{$('#chatPanel').classList.remove('open');$('#scrim').classList.remove('show');$('#chatPanel').setAttribute('aria-hidden','true')};$('#openChat').onclick=openChat;$('#closeChat').onclick=closeChat;$('#scrim').onclick=closeChat;
const openWillie=()=>{$('#williePanel').classList.add('open');$('#williePanel').setAttribute('aria-hidden','false')},closeWillie=()=>{$('#williePanel').classList.remove('open');$('#williePanel').setAttribute('aria-hidden','true')};$('#openWillie').onclick=openWillie;$('#closeWillie').onclick=closeWillie;$$('[data-go]').forEach(b=>b.onclick=()=>{closeWillie();document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'})});
let toastTimer;function showExternalToast(){clearTimeout(toastTimer);$('#siteToast').classList.add('show');toastTimer=setTimeout(()=>$('#siteToast').classList.remove('show'),3500)}document.addEventListener('click',e=>{const link=e.target.closest('a[href^="http"]');if(!link)return;link.target='_blank';link.rel='noopener';showExternalToast()});
let voiceEnabled=localStorage.getItem('khilaVoice')!=='off';
function setWillieMood(state,label){const panel=$('#williePanel');if(!panel)return;panel.classList.remove('willie-speaking','willie-listening','willie-thinking','willie-happy');panel.classList.add(`willie-${state}`);if($('#willieMood'))$('#willieMood').textContent=label||"Khila's site guide"}
function speak(text){if(!voiceEnabled||!('speechSynthesis'in window)||!text){setWillieMood('happy',"Khila's site guide");return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.96;utterance.pitch=.92;const voices=window.speechSynthesis.getVoices();utterance.voice=voices.find(v=>/david|mark|guy|daniel|george|male/i.test(v.name))||voices.find(v=>v.lang?.startsWith('en'))||null;utterance.onstart=()=>setWillieMood('speaking','Speaking...');utterance.onend=()=>setWillieMood('happy','Ready to help');utterance.onerror=()=>setWillieMood('happy','Ready to help');window.speechSynthesis.speak(utterance)}
function updateAudio(){if($('#audioIcon'))$('#audioIcon').textContent=voiceEnabled?'ON':'OFF';if($('#audioStatus'))$('#audioStatus').textContent=voiceEnabled?'Audio is on':'Audio is off'}updateAudio();
$('#audioToggle').onclick=()=>{voiceEnabled=!voiceEnabled;localStorage.setItem('khilaVoice',voiceEnabled?'on':'off');if(!voiceEnabled&&'speechSynthesis'in window)window.speechSynthesis.cancel();updateAudio();if(voiceEnabled)speak('Voice responses are now on.')};
$('#openWillie').addEventListener('click',()=>{setWillieMood('listening','Listening...');speak("Hi Khila! I'm Willie, your site guide. Choose a section and I'll help you get there.")});$$('[data-go]').forEach(b=>b.addEventListener('click',()=>speak(`Opening ${b.textContent.trim()}`)));
const utility=()=>{$('#utilityMenu').classList.toggle('open');$('#utilityToggle').classList.toggle('open');$('#utilityToggle').setAttribute('aria-expanded',$('#utilityMenu').classList.contains('open'))};$('#utilityToggle').onclick=utility;
const openAssistant=()=>{$('#assistantPanel').classList.add('open');$('#assistantPanel').setAttribute('aria-hidden','false');$('#utilityMenu').classList.remove('open');$('#utilityToggle').classList.remove('open');speak("Hi Khila! I'm your general ChatGPT assistant. What can I help you with?")},closeAssistant=()=>{$('#assistantPanel').classList.remove('open');$('#assistantPanel').setAttribute('aria-hidden','true')};$('#openAssistant').onclick=openAssistant;$('#closeAssistant').onclick=closeAssistant;
function addAssistantMessage(kind,text){$('#assistantMessages').insertAdjacentHTML('beforeend',`<div class="${kind}"></div>`);const el=$('#assistantMessages').lastElementChild;el.textContent=text;$('#assistantMessages').scrollTop=$('#assistantMessages').scrollHeight;return el}
const assistantHistory=[];$('#assistantForm').onsubmit=async e=>{e.preventDefault();const input=$('#assistantInput'),q=input.value.trim(),send=e.currentTarget.querySelector('button');if(!q||send.disabled)return;addAssistantMessage('user',q);assistantHistory.push({role:'user',content:q});input.value='';send.disabled=true;const loading=addAssistantMessage('bot','Thinking...');try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'general',messages:assistantHistory.slice(-10)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'The assistant is unavailable.');loading.textContent=data.reply;assistantHistory.push({role:'assistant',content:data.reply});speak(data.reply)}catch(error){loading.textContent=error.message}finally{send.disabled=false;input.focus()}};
$('#assistantForm').addEventListener('submit',()=>setWillieMood('thinking','Thinking...'),true);$('#chatForm').addEventListener('submit',()=>setWillieMood('thinking','Thinking...'),true);
new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1&&node.classList.contains('bot')&&node.textContent!=='Thinking…'&&node.textContent!=='Thinking...')speak(node.textContent)}))).observe($('#chatMessages'),{childList:true});
const chatHistory=[];
function addMessage(kind,text){$('#chatMessages').insertAdjacentHTML('beforeend',`<div class="${kind}"></div>`);$('#chatMessages').lastElementChild.textContent=text;$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;return $('#chatMessages').lastElementChild}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const i=$('#chatInput'),q=i.value.trim(),send=e.currentTarget.querySelector('button');if(!q||send.disabled)return;addMessage('user',q);chatHistory.push({role:'user',content:q});i.value='';send.disabled=true;const loading=addMessage('bot','Thinking…');try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({artist:$('#artistName').textContent,messages:chatHistory.slice(-10)})});const data=await response.json();if(!response.ok)throw new Error(data.error||'The assistant is unavailable.');loading.textContent=data.reply;chatHistory.push({role:'assistant',content:data.reply})}catch(error){loading.textContent=location.protocol==='file:'?'Start the secure Khila server first, then open http://localhost:8787.':error.message}finally{send.disabled=false;i.focus();$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}};
let timer,seconds=1500;$('#focusTimer').onclick=function(){if(timer){clearInterval(timer);timer=null;this.textContent='Resume '+format(seconds);return}timer=setInterval(()=>{seconds--;this.textContent='Pause '+format(seconds);if(seconds<=0){clearInterval(timer);timer=null;seconds=1500;this.textContent='Start 25:00';alert('Focus session complete!') }},1000)};function format(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').hidden=false});$('#installApp').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
